### ISSUE TITLE
Units of piecewise branches

### ISSUE THREAD

**Issue by MichaelClerx** [MichaelClerx/cellml-validation#39]
Spec doesn't say branches need to have same unit.

So things like this would be legal:

```
x = 1 [m]
    in [m]
y = (x == 1 [m] ? 5 [s] : 3 [V]) / (x == 1 [m] ? 3 [mol] : 4 [V*mol/s])
    in [s / mol]
```

**Comment by jonc125** [comment]
I think it's common sense that they should have the same units, otherwise the expression as a whole doesn't have well-defined units. You couldn't say assign to a variable. The whole thing would have to be wrapped in another piecewise which resolved the ambiguity, which you could just refactor as a single piecewise.

**Comment by MichaelClerx** [comment]
I agree! But it's not something the spec says, and see the example above

**Comment by skeating** [comment]
This is a difficult one. I spent some time trying to make unit calculator work out the units of the above but havent made it yet. Will put on hold till we decide whether its worth more time.

**Comment by MichaelClerx** [comment]
Sorry, didn't mean to post this as a cellmlmanip must, just a note about the spec!

**Comment by MichaelClerx** [comment]
Added more tests for this
